#!/bin/bash

# Script to configure Redis credentials for Supabase Edge Functions
# You need to run this with your Upstash Redis credentials

echo "==================================="
echo "Setup Redis Credentials for Supabase"
echo "==================================="
echo ""
echo "You need to get these values from your Upstash Dashboard:"
echo "1. Go to https://console.upstash.com/redis"
echo "2. Select your Redis database"
echo "3. Find REST API section"
echo "4. Copy UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN"
echo ""
echo "Then run these commands with your values:"
echo ""
echo "# Set the secrets using Supabase CLI:"
echo "supabase secrets set UPSTASH_REDIS_REST_URL=https://your-redis-url.upstash.io"
echo "supabase secrets set UPSTASH_REDIS_REST_TOKEN=your-redis-token"
echo ""
echo "# Or if you're using the dashboard:"
echo "Go to: https://supabase.com/dashboard/project/ierdfxgeectqoekugyvb/settings/vault"
echo ""
echo "Add these secrets:"
echo "- Name: UPSTASH_REDIS_REST_URL"
echo "- Value: Your Upstash Redis REST URL"
echo ""
echo "- Name: UPSTASH_REDIS_REST_TOKEN"  
echo "- Value: Your Upstash Redis REST Token"
echo ""
echo "After adding the secrets, the Edge Functions will automatically have access to them."
echo ""
echo "==================================="
echo "Your Railway service already has these configured."
echo "Now you need to add them to Supabase Edge Functions."
echo "==================================="